name: Build Apoena Release
run-name: ${{ github.actor }}
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Ensure we are on the release branch
        run: |
          if [ "${GITHUB_REF##*/}" != "release" ]; then
            echo "This workflow must run on the 'release' branch."
            exit 1
          fi

      - name: Build release
        run: |
          make apoena

      - name: Create Release on Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          name: ${{ github.run_number }}
          generate_release_notes: true
          prerelease: true
          files: |
            bin/*
